// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtddwYLFelx-QohNhoPDNPO2CBYImji24',
    appId: '1:513475357438:android:202b6f06b986e6716793af',
    messagingSenderId: '513475357438',
    projectId: 'personalcareertracker',
    storageBucket: 'personalcareertracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9qaBd7LT9KQih-Sy7mi2h8Xmx86mK2TY',
    appId: '1:513475357438:ios:c6ef644f331a48336793af',
    messagingSenderId: '513475357438',
    projectId: 'personalcareertracker',
    storageBucket: 'personalcareertracker.firebasestorage.app',
    iosBundleId: 'com.example.personalCareerTracking',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9xVAfYUgGIBn-ULEj2U9Qmhh5Rrb9SI8',
    appId: '1:513475357438:web:c6f5a42574e6c62d6793af',
    messagingSenderId: '513475357438',
    projectId: 'personalcareertracker',
    authDomain: 'personalcareertracker.firebaseapp.com',
    storageBucket: 'personalcareertracker.firebasestorage.app',
    measurementId: 'G-CXHY0279EC',
  );

}